from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from datetime import datetime
from typing import Protocol

from downloader_bot.domain import (
    DownloadArtifact,
    InviteCode,
    InviteRedemption,
    Job,
    JobStage,
    MediaPost,
    Platform,
    Progress,
    SelectionRequest,
    UserPreferences,
)

ProgressCallback = Callable[[Progress], Awaitable[None]]


class PlatformAdapter(Protocol):
    platform: Platform

    async def resolve(
        self, url: str, preferences: UserPreferences, *, audio_only: bool = False
    ) -> MediaPost: ...


class PlatformRegistry(Protocol):
    def detect(self, url: str) -> PlatformAdapter: ...


class Cancellation(Protocol):
    async def requested(self) -> bool: ...


class DownloadEngine(Protocol):
    async def download(
        self,
        post: MediaPost,
        job: Job,
        progress: ProgressCallback,
        cancellation: Cancellation,
    ) -> tuple[DownloadArtifact, ...]: ...


class JobQueue(Protocol):
    async def publish(self, job_id: str) -> str: ...
    def consume(
        self, consumer: str, *, block_ms: int = 5_000
    ) -> AsyncIterator[tuple[str, str]]: ...
    async def ack(self, message_id: str) -> None: ...
    async def reclaim(
        self, consumer: str, *, idle_ms: int
    ) -> tuple[tuple[str, str], ...]: ...


class JobRepository(Protocol):
    async def create_with_outbox(self, job: Job) -> tuple[Job, bool]: ...
    async def create_parent(self, job: Job) -> Job: ...
    async def create_batch(self, parent: Job, children: tuple[Job, ...]) -> None: ...
    async def get(self, job_id: str) -> Job | None: ...
    async def children(self, parent_id: str) -> tuple[Job, ...]: ...
    async def transition(
        self, job_id: str, expected: set[JobStage], stage: JobStage, **changes: object
    ) -> Job | None: ...
    async def request_cancel(self, job_id: str, user_id: int) -> Job | None: ...
    async def request_cancel_children(self, parent_id: str, user_id: int) -> int: ...
    async def bind_inline(
        self, job_id: str, user_id: int, inline_message_id: str
    ) -> Job | None: ...
    async def route_inline_to_private(self, job_id: str, user_id: int) -> Job | None: ...
    async def customize(
        self,
        job_id: str,
        user_id: int,
        *,
        audio_only: bool | None = None,
        document_mode: bool | None = None,
    ) -> Job | None: ...
    async def claim_outbox(self, limit: int = 100) -> tuple[tuple[int, str], ...]: ...
    async def mark_outbox_published(self, event_id: int) -> None: ...
    async def outstanding(self, limit: int = 100) -> tuple[str, ...]: ...
    async def queue_position(self, job_id: str) -> int | None: ...
    async def expired_artifacts(
        self, before: datetime, limit: int = 100
    ) -> tuple[str, ...]: ...
    async def mark_artifacts_cleaned(self, job_id: str, at: datetime) -> None: ...
    async def recent_for_user(
        self, user_id: int, *, limit: int = 10
    ) -> tuple[Job, ...]: ...


class SelectionRepository(Protocol):
    async def create(self, selection: SelectionRequest) -> SelectionRequest: ...
    async def get(self, token: str) -> SelectionRequest | None: ...
    async def update(
        self, token: str, user_id: int, now: datetime, **changes: object
    ) -> SelectionRequest | None: ...
    async def claim(
        self, token: str, user_id: int, now: datetime
    ) -> SelectionRequest | None: ...
    async def release_claim(
        self, token: str, user_id: int, claimed_at: datetime
    ) -> None: ...
    async def cancel(
        self, token: str, user_id: int, now: datetime
    ) -> SelectionRequest | None: ...


class UserRepository(Protocol):
    async def ensure(self, user_id: int) -> None: ...


class AccessRepository(Protocol):
    async def add_admin(self, user_id: int, *, added_by: int | None = None) -> bool: ...
    async def has_admin(self) -> bool: ...
    async def is_admin(self, user_id: int) -> bool: ...
    async def is_allowed(self, user_id: int) -> bool: ...
    async def create_invite(self, invite: InviteCode) -> bool: ...
    async def redeem_invite(
        self, code: str, user_id: int, now: datetime
    ) -> InviteRedemption: ...
    async def list_invites(
        self, created_by: int, now: datetime
    ) -> tuple[InviteCode, ...]: ...
    async def revoke_invite(self, code: str, admin_id: int, now: datetime) -> bool: ...


class SettingsRepository(Protocol):
    async def get(self, user_id: int) -> UserPreferences: ...
    async def save(
        self, user_id: int, preferences: UserPreferences
    ) -> UserPreferences: ...


class MediaCacheRepository(Protocol):
    async def get(self, key: str) -> tuple[DownloadArtifact, ...] | None: ...
    async def put(self, key: str, artifacts: tuple[DownloadArtifact, ...]) -> None: ...


class AnalyticsRepository(Protocol):
    async def record(
        self, event: str, *, user_id: int | None = None, job_id: str | None = None
    ) -> None: ...
    async def stats(self) -> dict[str, int]: ...


class ArtifactStore(Protocol):
    async def persist(
        self, job_id: str, artifacts: tuple[DownloadArtifact, ...]
    ) -> None: ...
    async def get(self, job_id: str) -> tuple[DownloadArtifact, ...]: ...
    async def cleanup(self, job_id: str) -> None: ...


class TelegramGateway(Protocol):
    async def delete_source(
        self,
        chat_id: int,
        message_id: int,
        business_connection_id: str | None = None,
    ) -> None: ...
    async def show_status(self, job: Job, progress: Progress) -> int | None: ...
    async def deliver(
        self,
        job: Job,
        artifacts: tuple[DownloadArtifact, ...],
        preferences: UserPreferences,
    ) -> bool | None: ...
    async def show_manual_retry(self, job: Job) -> None: ...


class ProgressBus(Protocol):
    async def publish(self, progress: Progress) -> None: ...
    def consume(self, consumer: str) -> AsyncIterator[Progress]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
    def monotonic(self) -> float: ...


class IdGenerator(Protocol):
    def new(self) -> str: ...
