#!/bin/sh
set -eu

repository_root=$(git rev-parse --show-toplevel)
gitleaks_image="ghcr.io/gitleaks/gitleaks:v8.30.1@sha256:c00b6bd0aeb3071cbcb79009cb16a60dd9e0a7c60e2be9ab65d25e6bc8abbb7f"
trivy_image="ghcr.io/aquasecurity/trivy:0.74.0@sha256:62b1e65e8869bc4b4c6aa4fa2b21595256c7c2f6018a9d9ad61caf87187c1969"

docker run --rm \
    --volume "$repository_root:/repo:ro" \
    "$gitleaks_image" \
    git /repo --no-banner --redact --timeout=300

docker run --rm \
    --volume "$repository_root:/repo:ro" \
    --volume media-pocket-trivy-cache:/root/.cache/trivy \
    "$trivy_image" \
    fs \
    --scanners vuln,misconfig \
    --severity HIGH,CRITICAL \
    --ignore-unfixed \
    --ignorefile /repo/.trivyignore.yaml \
    --exit-code 1 \
    --skip-dirs /repo/third_party \
    /repo
